hauzapp/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.base, name='home'),
    path('login/', views.LoginUser.as_view(), name='login_user'),
    path('forgot-password/', views.UserPasswordReset.as_view(), name='forgot_password'),
    path('register/', views.register_user, name='register_user'),
]

hauzapp/hauzapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('meetings/', include('meetings.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
]

hauzapp/users/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView

from . import views

app_name = 'users'
urlpatterns = [
    path('login/', LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('', include('django.contrib.auth.urls')),  # Include default auth urls.
    path('register/', views.register, name='register'),
]

hauzapp/dashboard/models.py
from django.db import models

# Create your models here.

hauzapp/dashboard/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm
from django.contrib.auth.models import User
from django import forms


class RegisterUserForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': "form-control form-control-user",
                                                     'placeholder': "Email Address"}))
    first_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control form-control-user',
                                                                              'id': 'exampleFirstName',
                                                                              'placeholder': 'First Name'}))
    last_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': "form-control form-control-user",
                                                                             'id': "exampleLastName",
                                                                             'placeholder': "Last Name"}))



    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(RegisterUserForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control form-control-user'
        self.fields['username'].widget.attrs['id'] = 'exampleFirstName'
        self.fields['username'].widget.attrs['placeholder'] = 'User Name'
        self.fields['password1'].widget.attrs['class'] = 'form-control form-control-user'
        self.fields['password1'].widget.attrs['id'] = 'examplePassword1'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['class'] = 'form-control form-control-user'
        self.fields['password2'].widget.attrs['id'] = 'examplePassword2'
        self.fields['password2'].widget.attrs['placeholder'] = 'Repeat Password'


class LoginUserForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(LoginUserForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control form-control-user'
        self.fields['username'].widget.attrs['id'] = 'exampleFirstName'
        self.fields['username'].widget.attrs['placeholder'] = 'User Name'
        self.fields['password'].widget.attrs['class'] = 'form-control form-control-user'
        self.fields['password'].widget.attrs['id'] = 'examplePassword'
        self.fields['password'].widget.attrs['placeholder'] = 'Password'


class UserPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': "form-control form-control-user",
                                                     'placeholder': "Enter Email Address..."}))

    class Meta:
        model = User
        fields = ('email',)

hauzapp/dashboard/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import login
from django.contrib.auth import views as auth_views
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from .forms import RegisterUserForm, LoginUserForm, UserPasswordResetForm


# Create your views here.

class LoginUser(auth_views.LoginView):
    model = User
    template_name = 'dashboard/pages/login_user.html'
    form_class = LoginUserForm
    success_url = '/'
    redirect_authenticated_user = True


class UserPasswordReset(auth_views.PasswordResetView):
    template_name = 'dashboard/pages/forgot_password.html'
    form_class = UserPasswordResetForm
    redirect_authenticated_user = True

@login_required
def base(request):
    return render(request, 'dashboard/includes/lorem.html')


def login_user(request):
    return render(request, 'dashboard/pages/login_user.html')


def forgot_password(request):
    return render(request, 'dashboard/pages/forgot_password.html')


def register_user(request):
    if request.user.is_authenticated:
        return redirect(reverse('dashboard:home'))
    if request.method != 'POST':
        # Display blank registration form
        form = RegisterUserForm()
    else:
        form = RegisterUserForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()

            # Log in new user
            login(request, new_user)
            return redirect('dashboard:home')

    # Display invalid or blank form
    return render(request, 'dashboard/pages/register_user.html', {'form': form})

hauzapp/dashboard/templates/dashboard/pages/forgot_password.html
{% extends 'dashboard/layouts/auth_base.html' %}

{% block content %}

<div class="text-center">
    <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
    <p class="mb-4">We get it, stuff happens. Just enter your email address below
        and we'll send you a link to reset your password!</p>
</div>
<form class="user" method="post" action="{% url 'dashboard:forgot_password' %}">
    <div class="form-group">
        {{ form.email }}
    </div>
    <button class="btn btn-primary btn-user btn-block" name="submit">
        Reset Password
    </button>
</form>
<hr>
<div class="text-center">
    <a class="small" href="{% url 'dashboard:register_user' %}">Create an Account!</a>
</div>
<div class="text-center">
    <a class="small" href="{% url 'dashboard:login_user' %}">Already have an account? Login!</a>
</div>

{% endblock content %}

hauzapp/dashboard/templates/dashboard/pages/login_user.html
{% extends 'dashboard/layouts/auth_base.html' %}

{% block content %}

<div class="text-center">
    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
</div>
<form class="user" method="post" action="{% url 'dashboard:login_user' %}">
    {% csrf_token %}
    <div class="form-group">
        {{ form.username }}
    </div>
    <div class="form-group">
        {{ form.password }}
    </div>
    <div class="form-group">
        <div class="custom-control custom-checkbox small">
            <input class="custom-control-input" id="customCheck" type="checkbox">
            <label class="custom-control-label" for="customCheck">Remember Me</label>
        </div>
    </div>
    <button class="btn btn-primary btn-user btn-block" name="submit">
        Login
    </button>

    {% if form.errors %}
    <div class="alert alert-danger">
        {{ form.errors }}
    </div>
    {% endif %}

<!--    [GOOGLE AND FACEBOOK] Registration-->
<!--    <hr>-->
<!--    <a class="btn btn-google btn-user btn-block" href="index.html">-->
<!--        <i class="fab fa-google fa-fw"></i> Login with Google-->
<!--    </a>-->
<!--    <a class="btn btn-facebook btn-user btn-block" href="index.html">-->
<!--        <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook-->
<!--    </a>-->
</form>
<hr>
<div class="text-center">
    <a class="small" href="{% url 'dashboard:forgot_password' %}">Forgot Password?</a>
</div>
<div class="text-center">
    <a class="small" href="{% url 'dashboard:register_user' %}">Create an Account!</a>
</div>

{% endblock content %}

hauzapp/dashboard/templates/dashboard/pages/register_user.html
{% extends 'dashboard/layouts/auth_base.html' %}

{% block content %}

<div class="text-center">
    <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
</div>
<form class="user" method="post" action="{% url 'dashboard:register_user' %}">
    {% csrf_token %}
    <div class="form-group row">
        <div class="col-sm-6 mb-3 mb-sm-0">
            {{ form.first_name }}
        </div>
        <div class="col-sm-6">
            {{ form.last_name }}
        </div>
    </div>
    <div class="form-group">
        {{ form.username }}
    </div>
    <div class="form-group">
        {{ form.email }}
    </div>
    <div class="form-group row">
        <div class="col-sm-6 mb-3 mb-sm-0">
            {{ form.password1 }}
        </div>
        <div class="col-sm-6">
            {{ form.password2 }}
        </div>
    </div>
    <button class="btn btn-primary btn-user btn-block" name="submit">
        Register Account
    </button>
<!--    [GOOGLE AND FACEBOOK] Registration-->
<!--    <hr>-->
<!--    <a class="btn btn-google btn-user btn-block" href="index.html">-->
<!--        <i class="fab fa-google fa-fw"></i> Register with Google-->
<!--    </a>-->
<!--    <a class="btn btn-facebook btn-user btn-block" href="index.html">-->
<!--        <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook-->
<!--    </a>-->
</form>
{% if form.errors %}
    <div class="alert alert-danger">
        {{ form.errors }}
    </div>
{% endif %}
<hr>
<div class="text-center">
    <a class="small" href="{% url 'dashboard:forgot_password' %}">Forgot Password?</a>
</div>
<div class="text-center">
    <a class="small" href="{% url 'dashboard:login_user' %}">Already have an account? Login!</a>
</div>

{% endblock content %}