hauzapp/hauzapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('meetings/', include('meetings.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
]

hauzapp/meetings/urls.py
from django.urls import path

from . import views

app_name = 'meetings'
urlpatterns = [
    path('new-meeting', views.create_meeting, name='new_meeting'),
    path('meeting-list/', views.MeetingList.as_view(), name='meeting_list'),
    path('meeting-list-message/<str:message>', views.meeting_list, name='meeting_list_message'),
    path('live-meeting/<unique_meeting_name>', views.meeting, name='meeting'),
]

hauzapp/users/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView

from . import views

app_name = 'users'
urlpatterns = [
    path('login/', LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('', include('django.contrib.auth.urls')),  # Include default auth urls.
    path('register/', views.register, name='register'),
]

hauzapp/meetings/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.utils import timezone
from django.utils.text import slugify
from datetime import timedelta


# Create your models here.
DEFAULT_HOST_ID = 1
class Meeting(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    host = models.ForeignKey(User, related_name='host', on_delete=models.CASCADE, default=DEFAULT_HOST_ID)
    title_of_meeting = models.CharField(max_length=150)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    duration = models.PositiveIntegerField(blank=True, null=True)
    starting_date_time = models.DateTimeField()
    ending_date_time = models.DateTimeField()
    unique_meeting_name = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'{self.creator}: {self.title_of_meeting}'

    def save(self, *args, **kwargs):
        if self.duration:
            self.ending_date_time = self.starting_date_time + timedelta(minutes=self.duration)
        else:
            self.ending_date_time = self.starting_date_time + timedelta(hours=1)
            self.duration = 60

        if not self.unique_meeting_name:
            self.unique_meeting_name = slugify(str(self.title_of_meeting)
                                               + '-'
                                               + str(uuid.uuid4()))

        if not self.host:
            self.host = 1

        return super(Meeting, self).save()

    @property
    def meeting_time(self):
        return (timezone.now() >= self.starting_date_time)

    @property
    def after_meeting(self):
        return (timezone.now() >= self.ending_date_time)

hauzapp/meetings/forms.py
from django import forms
from .models import Meeting


class MeetingCreateForm(forms.ModelForm):
    class Meta:
        model = Meeting
        fields = ["title_of_meeting",
                  "starting_date_time"
                  ]

        widgets = {
            "title_of_meeting": forms.TextInput(attrs={"class": "form-control", "placeholder":
                "Title of the Meeting..."}),
            "starting_date_time": forms.DateTimeInput(attrs={"class": "form-control date"})
        }

hauzapp/meetings/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, get_list_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.views import generic
from django.urls import reverse
from django.utils import timezone
from django.http import Http404

from .forms import MeetingCreateForm
from .models import Meeting


# Create your views here.
@login_required
def create_meeting(request):
    form = MeetingCreateForm()
    if request.method == 'POST':
        form = MeetingCreateForm(request.POST)
        if form.is_valid():
            fm = form.save(commit=False)
            fm.creator = request.user
            fm.save()

            return HttpResponseRedirect(reverse('meetings:meeting_list'))

    return render(request, 'meetings/create_meeting.html', {'form': form})

class MeetingList(generic.ListView):
    model = Meeting
    template_name = 'meetings/meeting_list.html'
    context_object_name = 'meetings'

    def get_queryset(self):
        return Meeting.objects.filter(creator=self.request.user).order_by('-starting_date_time')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(MeetingList, self).dispatch(request, *args, **kwargs)

@login_required
def meeting_list(request, message=None):
    """View only for reverse in view metting. Can be deleted after adding message showing utilities in MeetingList"""
    meetings = Meeting.objects.filter(creator=request.user).order_by('-starting_date_time')

    return render(request, 'meetings/meeting_list.html', {'meetings': meetings, 'message': message})

@login_required
def meeting(request, unique_meeting_name):
    message = None
    meeting = get_object_or_404(Meeting, unique_meeting_name=unique_meeting_name)

    if not (meeting.creator == request.user or meeting.host == request.user):
        raise Http404

    if not meeting.meeting_time:
        now = timezone.localtime()
        t = abs(now - meeting.starting_date_time).total_seconds()
        hours_get, minutes_get, seconds_get = seconds_to_time(t)

        message = (f'It is not the time for meeting {meeting.title_of_meeting}. Meeting starts in '
                   f'{hours_get}:{minutes_get}:{seconds_get}.')
        messages.warning(request, message)

        return HttpResponseRedirect(reverse(viewname='meetings:meeting_list_message', args=(message,)))

    elif meeting.after_meeting:
        now = timezone.localtime()
        t = abs(meeting.starting_date_time - now).total_seconds()
        hours_get, minutes_get, seconds_get = seconds_to_time(t)

        message = (f'The meeting {meeting.title_of_meeting} ended '
                   f'{hours_get}:{minutes_get}:{seconds_get} ago.')
        messages.warning(request, message)

        return HttpResponseRedirect(reverse(viewname='meetings:meeting_list_message', args=(message,)))

    if request.user == meeting.host:
        """render the view for meeting host"""
        return render(request, 'meetings/host_page.html', {'meeting': meeting})

    return render(request, 'meetings/meeting_page.html', {'meeting': meeting})


def seconds_to_time(t):
    minutes_get, seconds_get = divmod(t, 60)
    hours_get, minutes_get = divmod(minutes_get, 60)
    return hours_get, minutes_get, seconds_get

hauzapp/meetings/templates/meetings/create_meeting.html
{% extends 'dashboard/layouts/base.html' %}

{% block content %}
<div class="container-fluid">
    <h1 class="h3 mb-2 text-gray-800">Meeting table</h1>
    <p class="mb-4">Here you can find the table consists of all of your meeting in our app. If you want to create the
        new one, click <a href="{% url meeting:new_meeting}"
                          target="_blank">here</a>.</p>
    {% if message %}
    <div class="alert alert-danger">
        {{ message }}
    </div>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success btn-icon-split" name="submit">
            <span class="icon text-white-50">
                <i class="fas fa-check"></i>
            </span>
            <span class="text">Create Meeting</span>
        </button>
    </form>
</div>
{% endblock content %}

hauzapp/meetings/templates/meetings/host_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>Title: {{meeting.title_of_meeting}}</h2>
                    <div id="meet">

                    </div>
    {% block script %}
    <script src='https://meet.jit.si/external_api.js'></script>
    <script>
        const domain = 'meet.jit.si';
        const options = {
            roomName: '{{meeting.title_of_meeting}}',
            width: 1000,
            height: 600,
            parentNode: document.querySelector('#meet'),
            lang: 'en',  // default language, change the language to english
            configOverwrite: {
                startWithAudioMuted: true, // mute device audio by default
                startWithVideoMuted: true, // mute video by default
                prejoinPageEnabled: true, // enable prejoin page to set name
                enableLobbyChat: true,  // enable lobby chat
                localRecording: true,
                startWithAudioMuted: true,
                disableInitialGUM: true,

            },
            interfaceConfigOverwrite: {
                SHOW_CHROME_EXTENSION_BANNER: false, //ok
                TOOLBAR_ALWAYS_VISIBLE: true, // ok
                SETTINGS_SECTIONS: ['devices', 'language'],
                SHOW_POWERED_BY: false,
                TOOLBAR_ALWAYS_VISIBLE: true,
            },
            /* The toolbars that will be available for only the creator of the meeting */
            TOOLBAR_BUTTONS: ["microphone","camera","desktop","hangup","chat","raisehand","participants-pane","tileview","toggle-camera","invite","videoquality","livestreaming","mute-everyone","mute-video-everyone","sharedvideo","shareaudio","select-background","stats","settings","filmstrip"],
        };
    const api = new JitsiMeetExternalAPI(domain, options);
    </script>

    {% endblock %}
</body>
</html>

hauzapp/meetings/templates/meetings/meeting_list.html
{% extends 'dashboard/layouts/base.html' %}

{% block content %}
<div class="container-fluid">
    <h1 class="h3 mb-2 text-gray-800">Meeting table</h1>
    <p class="mb-4">Here you can find the table consists of all of your meeting in our app. If you want to create the
        new one, click <a href="{% url meeting:new_meeting}"
                          target="_blank">here</a>.</p>
    {% if message %}
    <div class="alert alert-danger">
        {{ message }}
    </div>
    {% endif %}
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Meetings</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table cellspacing="0" class="table table-bordered" id="dataTable" width="100%">
                    <thead>
                    <tr>
                    <tr>
                        <th>Title</th>
                        <th>Starting Date & Time</th>
                        <th>Duration</th>
                        <th>Architect</th>
                    </tr>
                    </thead>
                    {% for meeting in meetings %}
                    <tbody>
                    <tr>
                        <td>{{meeting.title_of_meeting}}</td>
                        <td>{{meeting.starting_date_time}}</td>
                        <td>{{meeting.duration}}</td>
                        <td>{{meeting.host.first_name}} {{meeting.host.last_name}}</td>
                        <td><input id="{{meeting.id}}" id="meeting_link" name="meeting_{{forloop.counter}}"
                                   type="hidden"
                                   value="{{ request.scheme }}://{{ request.get_host }}{% url 'meetings:meeting' meeting.unique_meeting_name %}">

                            <button class="btn btn-light btn-icon-split" onclick="myFunction('{{meeting.id}}')">
                                    <span class="icon text-gray-600">
                                        <i class="fas fa-arrow-right"></i>
                                    </span>
                                <span class="text">Copy Link</span>
                            </button>
                        </td>
                        <td><a class="btn btn-primary btn-icon-split"
                               href="{% url 'meetings:meeting' meeting.unique_meeting_name %}">
                                        <span class="icon text-white-50">
                                            <i class="fas fa-flag"></i>
                                        </span>
                            <span class="text">Join Meeting</span></a>
                        </td>
                    </tr>
                    </tbody>
                    {% endfor %}
                </table>
                <a class="btn btn-success btn-icon-split" href="{% url 'meetings:new_meeting' %}">
                                        <span class="icon text-white-50">
                                            <i class="fas fa-check"></i>
                                        </span>
                    <span class="text">Create New Meeting</span>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extra_js %}
<script>
        function myFunction(mid) {
            console.log(mid);
            //var myButtons = document.querySelectorAll('.myclass');
            var copyText = document.getElementById(mid);
            console.log(copyText);
            //copyText.select();
            //copyText.setSelectionRange(0, 99999);

            navigator.clipboard.writeText(copyText.value);
        alert("Meeting Link copied successfully to clipboard. ");
        }

</script>
{% endblock extra_js %}

hauzapp/meetings/templates/meetings/meeting_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>Title: {{meeting.title_of_meeting}}</h2>
                    <div id="meet">

                    </div>
    {% block script %}
    <script src='https://meet.jit.si/external_api.js'></script>
    <script>
        const domain = 'meet.jit.si'
        const options = {
            roomName: '{{meeting.title_of_meeting}}',
            width: 1000,
            height: 800,
            parentNode: document.querySelector('#meet'),
            lang: 'en',  // default language, change the language to english
            configOverwrite: {
                disableRemoteMute: true,  //DISABLE MUTE ALL FEATURE IN JITSI
                remoteVideoMenu: {
                    // If set to true the 'Kick out' button will be disabled for the guest.
                    disableKick: true
                },
            },
            interfaceConfigOverwrite: {
                filmStripOnly: true,
                /* the toolbars that will be visible for the guest of the meeting.*/
                TOOLBAR_BUTTONS: ['microphone', 'camera', 'closedcaptions', 'desktop',
                'fullscreen', 'fodeviceselection', 'chat', 'etherpad', 'raisehand', 'filmstrip', 'shortcuts', 'tileview','download', 'help','hangup'],
            }
        };
    const api = new JitsiMeetExternalAPI(domain, options);
    </script>

    {% endblock %}
</body>
</html>